import { Invitado } from "../types/invitado";

export const invitados: Invitado[] = [
  {
    id: "patricia-carranza",
    nombre: "Patricia",
    apellido: "Carranza",
    invitados: 3,
  },
  {
    id: "elsa-aguilar",
    nombre: "Elsa",
    apellido: "Aguilar",
    invitados: 1,
  },
  { id: "mauricio", nombre: "Mauricio", apellido: "", invitados: 2 },
  {
    id: "leti-salazar",
    nombre: "Leti",
    apellido: "Salazar",
    invitados: 1,
  },
  {
    id: "magali-hernandez",
    nombre: "Magali",
    apellido: "Hernandez",
    invitados: 1,
  },
  {
    id: "mileny-hernandez",
    nombre: "Mileny",
    apellido: "Hernandez",
    invitados: 1,
  },
  {
    id: "floridalma-boloz",
    nombre: "Floridalma",
    apellido: "Boloz",
    invitados: 1,
  },
  {
    id: "maria-beltran",
    nombre: "Maria",
    apellido: "Beltran",
    invitados: 2,
  },
  {
    id: "juana-cotzajay",
    nombre: "Juana",
    apellido: "Cotzajay",
    invitados: 2,
  },
  {
    id: "amelia-de-leon",
    nombre: "Amelia",
    apellido: "De León",
    invitados: 3,
  },
  {
    id: "gladiz-gramajo",
    nombre: "Gladiz",
    apellido: "Gramajo",
    invitados: 2,
  },
  {
    id: "jason-calderon",
    nombre: "Jason",
    apellido: "Calderón",
    invitados: 3,
  },
  {
    id: "jovani-perez",
    nombre: "Jovani",
    apellido: "Perez",
    invitados: 1,
  },
  { id: "ever", nombre: "Ever", apellido: "", invitados: 1 },
  {
    id: "evelyn-abad",
    nombre: "Evelyn",
    apellido: "Abad",
    invitados: 3,
  },
  { id: "antonia", nombre: "Antonia", apellido: "", invitados: 3 },
  {
    id: "teresa-guil",
    nombre: "Teresa",
    apellido: "Güil",
    invitados: 1,
  },
  {
    id: "magaly-chajon",
    nombre: "Magaly",
    apellido: "Chajon",
    invitados: 2,
  },
  {
    id: "berta-chajon",
    nombre: "Berta",
    apellido: "Chajon",
    invitados: 3,
  },
  {
    id: "katy-chajon",
    nombre: "Katy",
    apellido: "Chajon",
    invitados: 2,
  },
  {
    id: "candy-chajon",
    nombre: "Candy",
    apellido: "Chajon",
    invitados: 2,
  },
  {
    id: "marjorie-moraga",
    nombre: "Marjorie",
    apellido: "Moraga",
    invitados: 2,
  },
  {
    id: "kevin-armas",
    nombre: "Kevin",
    apellido: "Armas",
    invitados: 2,
  },
  {
    id: "eduardo-maquin",
    nombre: "Eduardo",
    apellido: "Maquin",
    invitados: 2,
  },
  {
    id: "lidia-perez",
    nombre: "Lidia",
    apellido: "Perez",
    invitados: 3,
  },
  {
    id: "claudia-cicimit",
    nombre: "Claudia",
    apellido: "Cicimit",
    invitados: 4,
  },
  {
    id: "claudia-rodas",
    nombre: "Claudia",
    apellido: "Rodas",
    invitados: 1,
  },
  {
    id: "beberly-leyba",
    nombre: "Beberly",
    apellido: "Leyba",
    invitados: 2,
  },
  {
    id: "jaqui-zurdo",
    nombre: "Jaqui",
    apellido: "Zurdo",
    invitados: 2,
  },
  {
    id: "cecilia-rivera",
    nombre: "Cecilia",
    apellido: "Rivera",
    invitados: 3,
  },
  {
    id: "paula-rivera",
    nombre: "Paula",
    apellido: "Rivera",
    invitados: 3,
  },
  {
    id: "herlinda-tun",
    nombre: "Herlinda",
    apellido: "Tun",
    invitados: 1,
  },
  {
    id: "birginia-marroquin",
    nombre: "Birginia",
    apellido: "Marroquin",
    invitados: 2,
  },
  { id: "omar", nombre: "Omar", apellido: "", invitados: 1 },
  { id: "milton", nombre: "Milton", apellido: "", invitados: 1 },
  {
    id: "paola-ibanes",
    nombre: "Paola",
    apellido: "Ibañes",
    invitados: 1,
  },
  {
    id: "alejandra-marcus",
    nombre: "Alejandra",
    apellido: "Marcus",
    invitados: 1,
  },
  { id: "yulisa", nombre: "Yulisa", apellido: "", invitados: 1 },
  { id: "yeimi", nombre: "Yeimi", apellido: "", invitados: 3 },
  {
    id: "margarita-caal",
    nombre: "Margarita",
    apellido: "Caal",
    invitados: 1,
  },
  {
    id: "evelyn-de-gomez",
    nombre: "Evelyn",
    apellido: "de Gomez",
    invitados: 3,
  },
  {
    id: "lucia-camposeco",
    nombre: "Lucia",
    apellido: "Camposeco",
    invitados: 3,
  },
  {
    id: "sheila-godinez",
    nombre: "Sheila",
    apellido: "Godinez",
    invitados: 2,
  },
  {
    id: "america-godinez",
    nombre: "América",
    apellido: "Godinez",
    invitados: 2,
  },
  {
    id: "brandon-camposeco",
    nombre: "Brandon",
    apellido: "Camposeco",
    invitados: 2,
  },
  {
    id: "helen-de-masariegos",
    nombre: "Helen",
    apellido: "De Masariegos",
    invitados: 3,
  },
  { id: "andrea", nombre: "Andrea", apellido: "", invitados: 2 },
  {
    id: "adan-ronquillo",
    nombre: "Adan",
    apellido: "Ronquillo",
    invitados: 8,
  },
  {
    id: "emanuel-perla",
    nombre: "Emanuel",
    apellido: "Perla",
    invitados: 1,
  },
  {
    id: "enrique-ambrocio",
    nombre: "Enrique",
    apellido: "Ambrocio",
    invitados: 4,
  },
  {
    id: "carlos-ambrocio",
    nombre: "Carlos",
    apellido: "Ambrocio",
    invitados: 4,
  },
  {
    id: "jose-ambrocio",
    nombre: "Jose",
    apellido: "Ambrocio",
    invitados: 2,
  },
  {
    id: "magaly-ambrocio",
    nombre: "Magaly",
    apellido: "Ambrocio",
    invitados: 3,
  },
  {
    id: "sergio-armas",
    nombre: "Sergio",
    apellido: "Armas",
    invitados: 3,
  },
  {
    id: "roberto-maida",
    nombre: "Roberto",
    apellido: "Maida",
    invitados: 3,
  },
  {
    id: "daniel-tojes",
    nombre: "Daniel",
    apellido: "Tojes",
    invitados: 2,
  },
  {
    id: "abigail-recinos",
    nombre: "Abigail",
    apellido: "Recinos",
    invitados: 2,
  },
  {
    id: "wendy-batzini",
    nombre: "Wendy",
    apellido: "Batzini",
    invitados: 3,
  },
];
